name: Windows Build (EXE)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.x"

    - name: Restore
      run: dotnet restore

    - name: Publish and capture binlog
      run: dotnet publish -c Release -r win-x64 /bl

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: msbuild-binlog
        path: '**/msbuild.binlog'

    - name: Upload EXE
      if: success()
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: CryptoAccessible-M0-exe
        path: '**/publish/**/*.exe'
